/*
 * Copyright © 2018 Mark Raynsford <code@io7m.com> http://io7m.com
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

package com.io7m.jcoronado.api;

/**
 * @see "VkBlendOp"
 */

public enum VulkanBlendOp implements VulkanEnumIntegerType
{
  /**
   * VK_BLEND_OP_ADD
   */

  VK_BLEND_OP_ADD(0),

  /**
   * VK_BLEND_OP_SUBTRACT
   */

  VK_BLEND_OP_SUBTRACT(1),

  /**
   * VK_BLEND_OP_REVERSE_SUBTRACT
   */

  VK_BLEND_OP_REVERSE_SUBTRACT(2),

  /**
   * VK_BLEND_OP_MIN
   */

  VK_BLEND_OP_MIN(3),

  /**
   * VK_BLEND_OP_MAX
   */

  VK_BLEND_OP_MAX(4),

  /**
   * VK_BLEND_OP_ZERO_EXT
   */

  VK_BLEND_OP_ZERO_EXT(1000148000),

  /**
   * VK_BLEND_OP_SRC_EXT
   */

  VK_BLEND_OP_SRC_EXT(1000148001),

  /**
   * VK_BLEND_OP_DST_EXT
   */

  VK_BLEND_OP_DST_EXT(1000148002),

  /**
   * VK_BLEND_OP_SRC_OVER_EXT
   */

  VK_BLEND_OP_SRC_OVER_EXT(1000148003),

  /**
   * VK_BLEND_OP_DST_OVER_EXT
   */

  VK_BLEND_OP_DST_OVER_EXT(1000148004),

  /**
   * VK_BLEND_OP_SRC_IN_EXT
   */

  VK_BLEND_OP_SRC_IN_EXT(1000148005),

  /**
   * VK_BLEND_OP_DST_IN_EXT
   */

  VK_BLEND_OP_DST_IN_EXT(1000148006),

  /**
   * VK_BLEND_OP_SRC_OUT_EXT
   */

  VK_BLEND_OP_SRC_OUT_EXT(1000148007),

  /**
   * VK_BLEND_OP_DST_OUT_EXT
   */

  VK_BLEND_OP_DST_OUT_EXT(1000148008),

  /**
   * VK_BLEND_OP_SRC_ATOP_EXT
   */

  VK_BLEND_OP_SRC_ATOP_EXT(1000148009),

  /**
   * VK_BLEND_OP_DST_ATOP_EXT
   */

  VK_BLEND_OP_DST_ATOP_EXT(1000148010),

  /**
   * VK_BLEND_OP_XOR_EXT
   */

  VK_BLEND_OP_XOR_EXT(1000148011),

  /**
   * VK_BLEND_OP_MULTIPLY_EXT
   */

  VK_BLEND_OP_MULTIPLY_EXT(1000148012),

  /**
   * VK_BLEND_OP_SCREEN_EXT
   */

  VK_BLEND_OP_SCREEN_EXT(1000148013),

  /**
   * VK_BLEND_OP_OVERLAY_EXT
   */

  VK_BLEND_OP_OVERLAY_EXT(1000148014),

  /**
   * VK_BLEND_OP_DARKEN_EXT
   */

  VK_BLEND_OP_DARKEN_EXT(1000148015),

  /**
   * VK_BLEND_OP_LIGHTEN_EXT
   */

  VK_BLEND_OP_LIGHTEN_EXT(1000148016),

  /**
   * VK_BLEND_OP_COLORDODGE_EXT
   */

  VK_BLEND_OP_COLORDODGE_EXT(1000148017),

  /**
   * VK_BLEND_OP_COLORBURN_EXT
   */

  VK_BLEND_OP_COLORBURN_EXT(1000148018),

  /**
   * VK_BLEND_OP_HARDLIGHT_EXT
   */

  VK_BLEND_OP_HARDLIGHT_EXT(1000148019),

  /**
   * VK_BLEND_OP_SOFTLIGHT_EXT
   */

  VK_BLEND_OP_SOFTLIGHT_EXT(1000148020),

  /**
   * VK_BLEND_OP_DIFFERENCE_EXT
   */

  VK_BLEND_OP_DIFFERENCE_EXT(1000148021),

  /**
   * VK_BLEND_OP_EXCLUSION_EXT
   */

  VK_BLEND_OP_EXCLUSION_EXT(1000148022),

  /**
   * VK_BLEND_OP_INVERT_EXT
   */

  VK_BLEND_OP_INVERT_EXT(1000148023),

  /**
   * VK_BLEND_OP_INVERT_RGB_EXT
   */

  VK_BLEND_OP_INVERT_RGB_EXT(1000148024),

  /**
   * VK_BLEND_OP_LINEARDODGE_EXT
   */

  VK_BLEND_OP_LINEARDODGE_EXT(1000148025),

  /**
   * VK_BLEND_OP_LINEARBURN_EXT
   */

  VK_BLEND_OP_LINEARBURN_EXT(1000148026),

  /**
   * VK_BLEND_OP_VIVIDLIGHT_EXT
   */

  VK_BLEND_OP_VIVIDLIGHT_EXT(1000148027),

  /**
   * VK_BLEND_OP_LINEARLIGHT_EXT
   */

  VK_BLEND_OP_LINEARLIGHT_EXT(1000148028),

  /**
   * VK_BLEND_OP_PINLIGHT_EXT
   */

  VK_BLEND_OP_PINLIGHT_EXT(1000148029),

  /**
   * VK_BLEND_OP_HARDMIX_EXT
   */

  VK_BLEND_OP_HARDMIX_EXT(1000148030),

  /**
   * VK_BLEND_OP_HSL_HUE_EXT
   */

  VK_BLEND_OP_HSL_HUE_EXT(1000148031),

  /**
   * VK_BLEND_OP_HSL_SATURATION_EXT
   */

  VK_BLEND_OP_HSL_SATURATION_EXT(1000148032),

  /**
   * VK_BLEND_OP_HSL_COLOR_EXT
   */

  VK_BLEND_OP_HSL_COLOR_EXT(1000148033),

  /**
   * VK_BLEND_OP_HSL_LUMINOSITY_EXT
   */

  VK_BLEND_OP_HSL_LUMINOSITY_EXT(1000148034),

  /**
   * VK_BLEND_OP_PLUS_EXT
   */

  VK_BLEND_OP_PLUS_EXT(1000148035),

  /**
   * VK_BLEND_OP_PLUS_CLAMPED_EXT
   */

  VK_BLEND_OP_PLUS_CLAMPED_EXT(1000148036),

  /**
   * VK_BLEND_OP_PLUS_CLAMPED_ALPHA_EXT
   */

  VK_BLEND_OP_PLUS_CLAMPED_ALPHA_EXT(1000148037),

  /**
   * VK_BLEND_OP_PLUS_DARKER_EXT
   */

  VK_BLEND_OP_PLUS_DARKER_EXT(1000148038),

  /**
   * VK_BLEND_OP_MINUS_EXT
   */

  VK_BLEND_OP_MINUS_EXT(1000148039),

  /**
   * VK_BLEND_OP_MINUS_CLAMPED_EXT
   */

  VK_BLEND_OP_MINUS_CLAMPED_EXT(1000148040),

  /**
   * VK_BLEND_OP_CONTRAST_EXT
   */

  VK_BLEND_OP_CONTRAST_EXT(1000148041),

  /**
   * VK_BLEND_OP_INVERT_OVG_EXT
   */

  VK_BLEND_OP_INVERT_OVG_EXT(1000148042),

  /**
   * VK_BLEND_OP_RED_EXT
   */

  VK_BLEND_OP_RED_EXT(1000148043),

  /**
   * VK_BLEND_OP_GREEN_EXT
   */

  VK_BLEND_OP_GREEN_EXT(1000148044),

  /**
   * VK_BLEND_OP_BLUE_EXT
   */

  VK_BLEND_OP_BLUE_EXT(1000148045);

  private final int value;

  VulkanBlendOp(final int i)
  {
    this.value = i;
  }

  @Override
  public int value()
  {
    return this.value;
  }
}
