name: main-openjdk_current-linux

on:
  push:
    branches: [ develop, feature/*, release/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Vulkan
        run: sudo apt install libvulkan1 mesa-vulkan-drivers vulkan-tools vulkan-validationlayers
      - name: Build
        run: mvn --errors clean verify site
      - name: Coverage
        uses: codecov/codecov-action@v1
        with:
          file: com.io7m.jcoronado.tests/target/site/jacoco/jacoco.xml
