name: main-openjdk_lts-linux

on:
  push:
    branches: [ develop, feature/*, release/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Vulkan
        run: sudo apt install libvulkan1 mesa-vulkan-drivers vulkan-tools vulkan-validationlayers
      - name: Build
        run: mvn --errors clean verify site
      - name: Show Driver
        run: cat /tmp/driver.txt
